--- 
knit: 'bookdown::publish_book(render = "local")'
title: "_Text as Data_ para Ciências Sociais"
subtitle: 'guia prático com aplicações'
author: "Davi Moreira"
date: "Criado em 02-08-2019. Atualizado em: `r format(Sys.Date(), '%d-%m-%Y')`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [biblioteca.bib, book.bib, packages.bib]
biblio-style: apalike
github-repo: https://github.com/davi-moreira/txt4cs
link-citations: yes
description: "Compilação de métodos e técnicas para análise automatizada de conteúdo"
urlcolor: blue  
---

<!---```{r setup,include=FALSE}
source("_setup.R",echo=FALSE)
```--->

# Prefácio {-}
```{r fig.width=2, fig.height=1.5, fig.align="center", echo=FALSE, message=FALSE, warning=F}
if(require(png) == F) install.packages('png'); require(png);
if(require(jpeg) == F) install.packages('jpeg'); require(jpeg);
if(require(grid) == F) install.packages('grid'); require(grid);

img <- readPNG("./images/txt4cs.png")
grid.raster(img)
```

A partir da produção de material para o curso _Text as Data_: análise automatizada de conteúdo que ministrei no [MQ-UFMG](http://www.fafich.ufmg.br/~mq/) em 2019 e no artigo que publiquei em coautoria com [Maurício Izumi](http://lattes.cnpq.br/2546701843557096) [@izumi_o_2018], esse livro tem como propósito difundir nas ciências sociais e humanidades técnicas e métodos de análise automatizada de conteúdo usando a linguagem `R`. 

## Objetivo {-}

O principal objetivo do livro é ser tutorial prático de uso e aplicação de técnicas e métodos de análise automatizada de conteúdo na língua portuguesa através da linguagem `R` .

## Sobre o autor/organizador {-}

Davi Moreira é Professor Adjunto da Escola de Relações Internacionais da Fundação Getulio Vargas. Ph.D. em Ciência Política pela Universidade de São Paulo (USP) e vencedor do Prêmio CAPES de tese 2017 na área de Ciência Política e Relações Internacionais. Atua nas seguintes áreas: políticas públicas, estudos legislativos, métodos quantitativos em ciências sociais e análise automatizada de conteúdo.

Para mais informações:

- [Página pessoal](https://davimoreira.com/). 

- [GitHub](https://github.com/davi-moreira) 

- [Google Scholar](https://scholar.google.com.br/citations?hl=pt-BR&user=dS9bbdMAAAAJ).

## Licença {-}

Este livro é distribuído de acordo com a licença  Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License ([<small>CC BY-NC-SA 4.0</small>](https://creativecommons.org/licenses/by-nc-sa/4.0/)).

## Agradecimentos {-}

Agradeço aos organizadores do MQ-UFMG 2019 pela oportunidade de ministrar o curso e assim me estimular a empreender esse projeto. Também agradeço aos amigos [Manoel Galdino](https://sites.google.com/site/galdinomcz/), [Rafael Magalhães](http://lattes.cnpq.br/8040086656965973), Lincon Ribeiro e [Umberto Mignozzetti](https://umbertomig.com/) pelo apoio e incentivo ao longo de toda minha trajetória como cientista. Por fim, agradeço à fantástica cientista de dados [Mônica Rocabado](https://rdados.netlify.app/), sem a qual esse projeto continuaria na gaveta.

Este livro é escrito com o uso do pacote **bookdown** [@R-bookdown], através do  `R Markdown` e **knitr** [@xie2015].

